Resistence table to list item
FACN7/feelit-chips-frontend pull request #29
Opened 2019-12-16 10:10 UTC by ebraheemabbas

add resistance table to list items
 on click at item fetch data from DB and get resistance table 
process the data and show it in table 
closes #28 closes #25

2019-12-16 15:37 UTC, jamiecoe commented
Remember to check what the layout looks like on a tablet in portrait mode

<img width="504" alt="Screen Shot 2019-12-16 at 17 06 01" src="https://user-images.githubusercontent.com/18463718/70920078-a3614e80-202a-11ea-9874-d9bc0fa7c41d.png">

2019-12-17 08:45 UTC, jamiecoe requested changes

2019-12-17 08:45 UTC, jamiecoe commented on src/components/curing-pages/Sensors-list-page/Sensors-list-page.jsx
> +  // }
Remove commented out code

2019-12-17 08:45 UTC, jamiecoe commented on src/components/curing-pages/Sensors-list-page/Sensors-list-page.jsx
> +let reducer = (table, action) => {
use `const` instead of `let`

2019-12-17 08:45 UTC, jamiecoe commented on src/components/curing-pages/Sensors-list-page/Sensors-list-page.jsx
> +const init = { s0: {}, s1: {}, s2: {}, s3: {}, s4: {}, s5: {}, s6: {}, s7: {} };
These should now be `a0` instead of `s0`, etc for other numbers.

Remember these now refer to **sensor areas** so we're using `a` instead of `s`

2019-12-17 08:45 UTC, jamiecoe commented on src/components/curing-pages/Sensors-list-page/Sensors-list-page.jsx
> +              history.goBack();
Using `history.goBack()` won't always work. What if I do this:
- start on google.com
- go straight to `http://localhost:3000/Sensors`, then click BACK button

It will take me back to google, not the home page!

You want to be specific - use `history.push('/')` to say always take user to homepage

2019-12-17 08:45 UTC, jamiecoe commented on src/components/curing-pages/Sensors-list-page/Sensors-list/list.jsx
> +const init = { s0: {}, s1: {}, s2: {}, s3: {}, s4: {}, s5: {}, s6: {}, s7: {} };
Use `a` instead of `s` (see previous comment)

2019-12-17 08:45 UTC, jamiecoe commented on src/components/curing-pages/Sensors-list-page/Sensors-list/list.jsx
> +            >
I'm not a fan of this `showMore` logic - it's confusing and unintuitive to understand. `showMore` sounds like it should be a boolean, but you're making it a number. I understand you don't want to make the fetch request again when hiding the drop down, but I think there is a better way to do it. Talk to me tomorrow about this tomorrow.

2019-12-17 10:58 UTC, okarem approved these changes

2019-12-17 13:12 UTC, jamiecoe approved these changes

2019-12-17 13:12 UTC, merged