Layout
FACN7/feelit-chips-frontend pull request #47
Opened 2019-12-18 13:26 UTC by ebraheemabbas

adding some style to the storage option
 closes #34

2019-12-18 18:46 UTC, jamiecoe requested changes

2019-12-18 18:46 UTC, jamiecoe commented on public/index.html
> +<html lang="en" style="height:100%;">
I would move this to `src/index.css`. Better to keep your CSS in on place, and could be confusing later on due to the order of [CSS selector specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity):

> Inline styles added to an element (e.g., style="font-weight: bold;") always overwrite any styles in external stylesheets, and thus can be thought of as having the highest specificity.

2019-12-19 08:25 UTC, jamiecoe approved these changes

2019-12-19 08:25 UTC, okarem approved these changes

2019-12-19 08:27 UTC, merged