small styling fixes and crediting icons
FACN7/feelit-chips-frontend pull request #58
Opened 2019-12-19 13:58 UTC by okarem

2019-12-19 15:01 UTC, ebraheemabbas approved these changes

2019-12-22 08:40 UTC, jamiecoe requested changes

2019-12-22 08:40 UTC, jamiecoe commented on src/components/Sensors-action-page/Sensors-actions.css
> +  /* height: 8rem; */
Don't leave commented out code pls 🙏🙏

2019-12-22 08:47 UTC, jamiecoe approved these changes

2019-12-22 08:47 UTC, merged